/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The Passwords model module.
 * @module model/Passwords
 * @version 1.0.0
 */
export default class Passwords {
  /**
   * Constructs a new <code>Passwords</code>.
   * @alias module:model/Passwords
   * @class
   * @param password {String} 
   * @param confirmation {String} 
   */
  constructor(password, confirmation) {
    this.password = password;
    this.confirmation = confirmation;
  }

  /**
   * Constructs a <code>Passwords</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Passwords} obj Optional instance to populate.
   * @return {module:model/Passwords} The populated <code>Passwords</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Passwords();
      if (data.prototype.hasOwnProperty.call(entries, 'password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.prototype.hasOwnProperty.call(entries, 'confirmation'))
        obj.confirmation = ApiClient.convertToType(data['confirmation'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} password
 */
Passwords.prototype.password = undefined;

/**
 * @member {String} confirmation
 */
Passwords.prototype.confirmation = undefined;

