/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The RefreshTokenRequest model module.
 * @module model/RefreshTokenRequest
 * @version 1.0.0
 */
export default class RefreshTokenRequest {
  /**
   * Constructs a new <code>RefreshTokenRequest</code>.
   * @alias module:model/RefreshTokenRequest
   * @class
   * @param refreshToken {String} 
   */
  constructor(refreshToken) {
    this.refreshToken = refreshToken;
  }

  /**
   * Constructs a <code>RefreshTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefreshTokenRequest} obj Optional instance to populate.
   * @return {module:model/RefreshTokenRequest} The populated <code>RefreshTokenRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RefreshTokenRequest();
      if (data.prototype.hasOwnProperty.call(entries, 'refresh_token'))
        obj.refreshToken = ApiClient.convertToType(data['refresh_token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} refreshToken
 */
RefreshTokenRequest.prototype.refreshToken = undefined;

