/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The SignRequest model module.
 * @module model/SignRequest
 * @version 1.0.0
 */
export default class SignRequest {
  /**
   * Constructs a new <code>SignRequest</code>.
   * @alias module:model/SignRequest
   * @class
   * @param login {String} 
   * @param password {String} 
   */
  constructor(login, password) {
    this.login = login;
    this.password = password;
  }

  /**
   * Constructs a <code>SignRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignRequest} obj Optional instance to populate.
   * @return {module:model/SignRequest} The populated <code>SignRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SignRequest();
      if (data.prototype.hasOwnProperty.call(entries, 'login'))
        obj.login = ApiClient.convertToType(data['login'], 'String');
      if (data.prototype.hasOwnProperty.call(entries, 'password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} login
 */
SignRequest.prototype.login = undefined;

/**
 * @member {String} password
 */
SignRequest.prototype.password = undefined;

