/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The SignResponse model module.
 * @module model/SignResponse
 * @version 1.0.0
 */
export default class SignResponse {
  /**
   * Constructs a new <code>SignResponse</code>.
   * @alias module:model/SignResponse
   * @class
   * @param accessToken {String} 
   * @param refreshToken {String} 
   * @param tfaEnabled {Boolean} 
   */
  constructor(accessToken, refreshToken, tfaEnabled) {
    this.accessToken = accessToken;
    this.refreshToken = refreshToken;
    this.tfaEnabled = tfaEnabled;
  }

  /**
   * Constructs a <code>SignResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignResponse} obj Optional instance to populate.
   * @return {module:model/SignResponse} The populated <code>SignResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SignResponse();
      if (data.prototype.hasOwnProperty.call(entries, 'access_token'))
        obj.accessToken = ApiClient.convertToType(data['access_token'], 'String');
      if (data.prototype.hasOwnProperty.call(entries, 'refresh_token'))
        obj.refreshToken = ApiClient.convertToType(data['refresh_token'], 'String');
      if (data.prototype.hasOwnProperty.call(entries, 'tfa_enabled'))
        obj.tfaEnabled = ApiClient.convertToType(data['tfa_enabled'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} accessToken
 */
SignResponse.prototype.accessToken = undefined;

/**
 * @member {String} refreshToken
 */
SignResponse.prototype.refreshToken = undefined;

/**
 * @member {Boolean} tfaEnabled
 */
SignResponse.prototype.tfaEnabled = undefined;

