/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The StatusCode model module.
 * @module model/StatusCode
 * @version 1.0.0
 */
export default class StatusCode {
  /**
   * Constructs a new <code>StatusCode</code>.
   * @alias module:model/StatusCode
   * @class
   * @param code {Number} 
   * @param name {String} 
   */
  constructor(code, name) {
    this.code = code;
    this.name = name;
  }

  /**
   * Constructs a <code>StatusCode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatusCode} obj Optional instance to populate.
   * @return {module:model/StatusCode} The populated <code>StatusCode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StatusCode();
      if (data.prototype.hasOwnProperty.call(entries, 'code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.prototype.hasOwnProperty.call(entries, 'name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
StatusCode.prototype.code = undefined;

/**
 * @member {String} name
 */
StatusCode.prototype.name = undefined;

