/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { entries } from 'core-js/actual/array';
import ApiClient from '../ApiClient';

/**
 * The VerificationRequest model module.
 * @module model/VerificationRequest
 * @version 1.0.0
 */
export default class VerificationRequest {
  /**
   * Constructs a new <code>VerificationRequest</code>.
   * @alias module:model/VerificationRequest
   * @class
   * @param username {String} 
   * @param code {String} 
   */
  constructor(username, code) {
    this.username = username;
    this.code = code;
  }

  /**
   * Constructs a <code>VerificationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerificationRequest} obj Optional instance to populate.
   * @return {module:model/VerificationRequest} The populated <code>VerificationRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerificationRequest();
      if (data.prototype.hasOwnProperty.call(entries, 'username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.prototype.hasOwnProperty.call(entries, 'code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
VerificationRequest.prototype.username = undefined;

/**
 * @member {String} code
 */
VerificationRequest.prototype.code = undefined;

