version: '3.8'

services:
  app:
    image: mig-api:latest
    container_name: app
    build:
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mig
      - SPRING_DATASOURCE_USERNAME=ivan
      - SPRING_DATASOURCE_PASSWORD=pASSword
    networks:
      app-network:
        ipv4_address: 192.168.112.3
      redis-network:
        ipv4_address: 192.168.128.3
    expose:
      - 8080
    volumes:
      - type: volume
        source: api-volume
        target: /tmp/mig-app/api
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: db
    command:
      - 'postgres'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=pASSword
      - POSTGRES_DB=mig
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      app-network:
        ipv4_address: 192.168.112.2
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data/pgdata
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ivan -d mig']
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 90s

  redis:
    image: redis
    container_name: redis
    networks:
      redis-network:
        ipv4_address: 192.168.128.2
    ports:
      - '6379:6379'

  front:
    image: front
    container_name: front
    build:
      context: ./kemsu-vue-app
      dockerfile: ./docker/prod/Dockerfile
    volumes:
      - type: volume
        source: vue-dist
        target: /front/dist
    depends_on:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      app-network:
        ipv4_address: 192.168.112.5
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/local-conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: vue-dist
        target: /var/www/html
    depends_on:
      - front

networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/20
          gateway: 192.168.128.1
  app-network:
    ipam:
      config:
        - subnet: 192.168.112.0/20
          gateway: 192.168.112.1

volumes:
  vue-dist:
    driver: local
  db-volume:
    driver: local
  api-volume:
    driver: local
  pgadmin-volume:
    driver: local