version: '0.0.9'

services:
  app:
    container_name: app
    image: 'mig-api:latest'
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    expose:
      - 8080
    depends_on:
      - db
      - nginx
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mig
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - app-network
      - redis_app_net
    volumes:
      - /tmp/mig-api:/tmp/mig-api

  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mig
    ports:
      - 5432:5432
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis_app_net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  redis_app_net:
    driver: bridge
  app-network:
    driver: bridge