name: deeplom
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.1.2
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/