name: deeplom
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  go_router: ^14.1.4
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  file_picker: ^8.0.3
  http: ^1.2.1
  shared_preferences: any
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1

  intl: any
flutter_intl:
  enabled: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/charles.pem