server:
  port: 8888

spring:
  application:
    name: admin-backend

  docker:
    compose:
      enabled: true
      file: admin-compose.yaml

  flyway:
    locations:
      - classpath:/db/migration

management:
  endpoints:
    web:
      exposure:
        include: '*'
