spring:
  application:
    name: mig-api
  datasource:
    username: postgres
    password: 25d45DbD3f5CA3b3F-gD6E*CaaEgBbb*
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:11498/mig
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivan.duvanov.3@gmail.com
    password: pilnamucvqamgbnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  flyway:
    locations:
      - classpath:/db/migration
#      - classpath:/db/callback

mig:
  jwt:
    secret: nevergonnagiveyouupnevergonnaletyoudownnevergonnarunaroundanddesertyou
    expiration-ms: 1440000
    refresh-expiration: 10080000
    verification-expiration: 1440000
server:
  port: 8080