spring:
  application:
    name: mig-api
  datasource:
    username: ivan # postgres
    password: 1234 # 25d45DbD3f5CA3b3F-gD6E*CaaEgBbb*
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mig # jdbc:postgresql://viaduct.proxy.rlwy.net:11498/mig
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivan.duvanov.3@gmail.com
    password: pilnamucvqamgbnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      ttl: 10000
  flyway:
    locations:
      - classpath:/db/migration
#      - classpath:/db/callback

mig:
  jwt:
    secret: nevergonnagiveyouupnevergonnaletyoudownnevergonnarunaroundanddesertyou
    expiration-ms: 1440000
    refresh-expiration: 604800000
    verification-expiration: 2628000000
  tfa:
    expiration-ms: 600000
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /api/swagger/swagger-ui
  api-docs:
    enabled: true
    path: /api/swagger/api-docs

management:
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info, metric'
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  config: classpath:logback-dev.xml