server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
#    pipeline_stages:
#      - regex:
#          expression:
#            \[(?P<time>.*?)\] \[(?P<tenantid>.*?)\] \[(?P<severity>.*?)\] \[(?P<module>.*?)\] \[(?P<msg>.*?)\]
#      - labels:
#          tenantid:
#          severity:
#          module:
#      - timestamp:
#          format: 02.01.2006 15:04:05
#          source: time
#          location: Asia/Krasnoyarsk
#      - labeldrop:
#          - filename
#          - time
#      - template:
#          source: msgData
#          template: '{{ .msg }}'
#      - output:
#          source: msgData
#  - job_name: docker
#    pipeline_stages:
#      - docker: {}
#    static_configs:
#      - labels:
#          job: docker
#          __path__: /var/lib/docker/containers/*/*-json.log