/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Error from './model/Error';
import Passwords from './model/Passwords';
import RefreshTokenRequest from './model/RefreshTokenRequest';
import SignRequest from './model/SignRequest';
import SignResponse from './model/SignResponse';
import StatusCode from './model/StatusCode';
import VerificationRequest from './model/VerificationRequest';
import AdminControllerApi from './api/AdminControllerApi';
import AuthenticationControllerApi from './api/AuthenticationControllerApi';

/**
* Client library of swagger-js-client.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SwaggerJsClient = require('index'); // See note below*.
* var xxxSvc = new SwaggerJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SwaggerJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SwaggerJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SwaggerJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Passwords model constructor.
     * @property {module:model/Passwords}
     */
    Passwords,

    /**
     * The RefreshTokenRequest model constructor.
     * @property {module:model/RefreshTokenRequest}
     */
    RefreshTokenRequest,

    /**
     * The SignRequest model constructor.
     * @property {module:model/SignRequest}
     */
    SignRequest,

    /**
     * The SignResponse model constructor.
     * @property {module:model/SignResponse}
     */
    SignResponse,

    /**
     * The StatusCode model constructor.
     * @property {module:model/StatusCode}
     */
    StatusCode,

    /**
     * The VerificationRequest model constructor.
     * @property {module:model/VerificationRequest}
     */
    VerificationRequest,

    /**
    * The AdminControllerApi service constructor.
    * @property {module:api/AdminControllerApi}
    */
    AdminControllerApi,

    /**
    * The AuthenticationControllerApi service constructor.
    * @property {module:api/AuthenticationControllerApi}
    */
    AuthenticationControllerApi
};
