name: Master CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Grand executive permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Gradlew clean
#        run: ./gradlew clean
#
#      - name: Gradlew test run
#        id: test
#        run: ./gradlew test
#
#      - name: Successful tests
#        if: steps.test.outcome != 'success'
#        run: |
#          echo "Tests error"
#          exit 1

      - name: Successful build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME }}
          token: ${{ secrets.TELEGRAM_NOT }}
          message: |
            ✅ Application build done
            Check report on https://github.com/IvanDuvanOFF/mig-api/actions

      - name: Send alert in Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME }}
          token: ${{ secrets.TELEGRAM_NOT }}
          message: |
            ❌ Failed to build
            Check report on https://github.com/IvanDuvanOFF/mig-api/actions
