name: Master pull-request CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-api:
    name: Compile and test application

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Grand executive permission for gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      - name: Gradlew clean
        working-directory: ./backend
        run: ./gradlew clean

      - name: Gradlew test run
        id: test
        working-directory: ./backend
        run: ./gradlew test

      - name: Successful tests
        if: steps.test.outcome != 'success'
        run: |
          echo "Tests error"
          exit 1

      - name: Vuejs test build
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Successful build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME }}
          token: ${{ secrets.TELEGRAM_NOT }}
          message: |
            ✅ Application tests done
            Check report on https://github.com/${{ github.repository }}/actions

      - name: Send alert in Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME }}
          token: ${{ secrets.TELEGRAM_NOT }}
          message: |
            ❌ Tests failed
            Check report on https://github.com/${{ github.repository }}/actions